<a href="https://colab.research.google.com/github/JaymariePasno/Linear-Algebra/blob/main/Long_Quiz_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [52]:
import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6]])
print('A = ',A)

B = np.array([[1, 2], [3, 4], [5, 6]])
print('B = ',B)

C = np.array([[1, 2, 3], [4, 5, 6],[7, 8, 9]])
print('C = ',C)

D = np.array([[1, 2], [3, 4]])
print('D = ',D)
print("")

a = np.dot(A,B)
print('a. AB')
print('a = ',a)
print("")

b = D+D
print('b. D+D')
print('b = ',b)
print("")

c = 2*C
print('c. 2C')
print('c = ',c)

A =  [[1 2 3]
 [4 5 6]]
B =  [[1 2]
 [3 4]
 [5 6]]
C =  [[1 2 3]
 [4 5 6]
 [7 8 9]]
D =  [[1 2]
 [3 4]]

a. AB
a =  [[22 28]
 [49 64]]

b. D+D
b =  [[2 4]
 [6 8]]

c. 2C
c =  [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [53]:
import numpy as np

A=np.array([2,7,4])
B=np.array([3,9,8])

output = np.cross(A,B)
print(output)

[20 -4 -3]
