<a href="https://colab.research.google.com/github/JaymariePasno/58013_LinearAlgebra/blob/main/Python_Exercise_9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

A = np.array([
    [1,4],
    [0,3]
])
print(int(np.linalg.det(A)))

B = np.array([
    [1,3,5,6],
    [0,3,1,3],
    [3,1,8,2],
    [5,2,6,8]
])
print(int(np.linalg.det(B)))


3
-235


In [7]:

import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

C = np.array([[2, 0, -2],
              [1, 3, 5],
              [-1, -4, -6]])

# 1. Distributive Property
left_side = A.dot(B + C)
right_side = A.dot(B) + A.dot(C)
print("1. Distributive Property:")
print("A(B + C) =", left_side)
print("AB + AC =", right_side)
print(np.array_equal(left_side, right_side))

# 2. Associative Property
left_side = (A.dot(B)).dot(C)
right_side = A.dot(B.dot(C))
print("\n2. Associative Property:")
print("(AB)C =", left_side)
print("A(BC) =", right_side)
print(np.array_equal(left_side, right_side))

# 3. Scalar Multiplication Distributive Property
k = 2
left_side = k * (A.dot(B))
right_side = (k * A).dot(B)
print("\n3. Scalar Multiplication Distributive Property:")
print("k(AB) =", left_side)
print("(kA)B =", right_side)
print(np.array_equal(left_side, right_side))

# 4. Identity Matrix Property
I = np.identity(3)
left_side = I.dot(A)
right_side = A.dot(I)
print("\n4. Identity Matrix Property:")
print("IA =", left_side)
print("AI =", right_side)
print(np.array_equal(left_side, A) and np.array_equal(right_side, A))

# 5. Multiplicative Property of Zero
zero_matrix = np.zeros((3, 3))
left_side = zero_matrix.dot(A)
right_side = A.dot(zero_matrix)
print("\n5. Multiplicative Property of Zero:")
print("0A =", left_side)
print("A0 =", right_side)
print(np.array_equal(left_side, zero_matrix) and np.array_equal(right_side, zero_matrix))

# 6. Transpose Property
left_side = (A.dot(B)).T
right_side = (B.T).dot(A.T)
print("\n6. Transpose Property:")
print("(AB)^T =", left_side)
print("B^T * A^T =", right_side)
print(np.array_equal(left_side, right_side))

1. Distributive Property:
A(B + C) = [[ 31  18   8]
 [ 91  60  35]
 [151 102  62]]
AB + AC = [[ 31  18   8]
 [ 91  60  35]
 [151 102  62]]
True

2. Associative Property:
(AB)C = [[  66    0  -48]
 [ 183   -9 -147]
 [ 300  -18 -246]]
A(BC) = [[  66    0  -48]
 [ 183   -9 -147]
 [ 300  -18 -246]]
True

3. Scalar Multiplication Distributive Property:
k(AB) = [[ 60  48  36]
 [168 138 108]
 [276 228 180]]
(kA)B = [[ 60  48  36]
 [168 138 108]
 [276 228 180]]
True

4. Identity Matrix Property:
IA = [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
AI = [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
True

5. Multiplicative Property of Zero:
0A = [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
A0 = [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
True

6. Transpose Property:
(AB)^T = [[ 30  84 138]
 [ 24  69 114]
 [ 18  54  90]]
B^T * A^T = [[ 30  84 138]
 [ 24  69 114]
 [ 18  54  90]]
True
