<a href="https://colab.research.google.com/github/JaymariePasno/58013_LinearAlgebra/blob/main/Python_Exercise_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

A = np.array([[1,2,3],[4,5,6],[7,8,9]])
A1 = np.array([[1,2],[4,7]])

print (A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
deter = np.linalg.det(A)

print(deter)

0.0


In [4]:
try:
  B = np.linalg.inv(A)

  print("Inverse of Matrix A: ")
  print(B)

except np.linalg.LinAlgError:
    print("Matrix A is singular and doesn't have an inverse.")

Matrix A is singular and doesn't have an inverse.


In [5]:
A1 = np.array([[1,2],[4,7]])
invA = np.linalg.inv(A1)
print(invA)

[[-7.  2.]
 [ 4. -1.]]


In [6]:
#Python Program to Transpose a 4x4 Matrix

A= ([[6,1,1,3],[4,-2,5,1],[2,8,7,6],[3,1,9,7]])
A= np.array([[6,1,1,3],[4,-2,5,1],[2,8,7,6],[3,1,9,7]])


print(A)
print("\n")

B=(np.transpose(A))

print(B)

[[ 6  1  1  3]
 [ 4 -2  5  1]
 [ 2  8  7  6]
 [ 3  1  9  7]]


[[ 6  4  2  3]
 [ 1 -2  8  1]
 [ 1  5  7  9]
 [ 3  1  6  7]]
