<a href="https://colab.research.google.com/github/JaymariePasno/LinearAlgebra/blob/main/Python_Exercise_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

X = np.array([
    [1,1,1],
    [3,-2,-1],
    [-1,4,2]
], dtype=float)
Y = np.array([
    [1],
    [4],
    [-3]
],dtype=float)
print(X)
print(X.shape, "\n")
print(Y)
print(Y.shape)


[[ 1.  1.  1.]
 [ 3. -2. -1.]
 [-1.  4.  2.]]
(3, 3) 

[[ 1.]
 [ 4.]
 [-3.]]
(3, 1)


In [7]:
import numpy as np

quantities = np.array([[30,10,120],[40,20,200],[50,40,360]])
total_cost = np.array([12500,18000,25700])

A = quantities

B = total_cost

prices = np.linalg.solve(A,B)
price_per_sack_of_flour, price_per_pack_of_yeast, price_per_egg = prices

print(f"Price per sack of flour: {price_per_sack_of_flour:.2f} pesos")
print(f"Price per pack of yeast: {price_per_pack_of_yeast:.2f} pesos")
print(f"Price per egg: {price_per_egg:.2f} pesos")

Price per sack of flour: 330.00 pesos
Price per pack of yeast: 140.00 pesos
Price per egg: 10.00 pesos
